version: '3'

services:
  next-app:
    build: .
    container_name: next-app
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./data:/usr/src/app/data
    networks:
      - frontnetwok
networks:
  frontnetwok:
    name: 'frontnetwok'
