import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lima",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="relative">
      {/* <div className="w-full mt-0  absolute top-0  bg-[url(/assets/dot.png)] bg-repeat h-[100%] min-h-100vh"></div> */}
      {/* <div className="w-full grad-top  fixed top-20 !z-40  h-[1500px] min-h-100vh"></div> */}
      {children}
    </div>
  );
}
